{% set name = "oslo.config" %}
{% set version = "8.3.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "dfbb83dc5b4c86ddf8b96f3967252f17586a67f2cef65309df2fd510bf9e87fc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pbr >=2.0.0

  run:
    - python
    - debtcollector >=1.2.0
    - netaddr >=0.7.18
    - stevedore >=1.20.0
    - oslo.i18n >=3.15.3
    - rfc3986 >=1.2.0
    - pyyaml >=3.12
    - requests >=2.18.0
    - importlib_metadata >=1.7.0  # [py<38]

test:
  imports:
    - oslo_config
    - oslo_config.cfg
    - oslo_config.types

about:
  home: http://docs.openstack.org/developer/oslo.config/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: The Oslo configuration API supports parsing command line arguments and .ini style configuration files.
  doc_url: http://docs.openstack.org/developer/oslo.config/
  dev_url: http://git.openstack.org/cgit/openstack/oslo.config

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
    - tschoonj
