# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IDZBCcND+pOEUuY6t/dwstAmnssCt0IPmBLy2ifJqcAc5u7gqnfZancoFnot0jdvDcCS4nycpwv8bMXmrmslYB7zAwEWw6RqGante5hA/P2YYMRlyQl48DUXctTZgeIBWgEidwGHOkPt7wagtrL9/EYsx4l8y+JbQ1+ikfFb3LYWU9jbbE5XledGIBBG8fcntzaB06FbfsFFXyD3NveFr0pra0uozYqadlVgWifjxJgTUQXol+GtEqKyCgM+AbTBvUj5SdgfKlvnMmQCXhTX0P0wdhb5ugN5h79cdkV3rNqylouPDVhjYVjB+Sjbu+omV/5rFBK7v67CNoIBJlKi4Z1tjSDFUHbNii9EahKBARTEdf1xaLjAhb1tDahv2hjGiPJYDTOzMoiW0CfMY0VF6DUc4G+w4u0zz7CX9Ndv4TuelBRy8hUaSrCzqvwURv7qJzlxF3UGfXQj5sfQHaMGDn3EiIAcvlpRf9bNasVZmwgKLHz4NXKEFuAO7ukkuY1enQqdXF0oRMf8/87OOTG/70uGeWdrUPM8x+iPplDmjMHecMuWHkuJ7H2cB8b0yADT1hOCc9hIEMs556POB31+l+Ze9jGOF3t9K6DgwNX+V4msP6+and7JUUDzW9MPeD0PzU2QaYZLQDdhXU3o1YMkrXg1e8VWop2jFGY47chwsVc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
