travis:
  secure:
    BINSTAR_TOKEN: IDZBCcND+pOEUuY6t/dwstAmnssCt0IPmBLy2ifJqcAc5u7gqnfZancoFnot0jdvDcCS4nycpwv8bMXmrmslYB7zAwEWw6RqGante5hA/P2YYMRlyQl48DUXctTZgeIBWgEidwGHOkPt7wagtrL9/EYsx4l8y+JbQ1+ikfFb3LYWU9jbbE5XledGIBBG8fcntzaB06FbfsFFXyD3NveFr0pra0uozYqadlVgWifjxJgTUQXol+GtEqKyCgM+AbTBvUj5SdgfKlvnMmQCXhTX0P0wdhb5ugN5h79cdkV3rNqylouPDVhjYVjB+Sjbu+omV/5rFBK7v67CNoIBJlKi4Z1tjSDFUHbNii9EahKBARTEdf1xaLjAhb1tDahv2hjGiPJYDTOzMoiW0CfMY0VF6DUc4G+w4u0zz7CX9Ndv4TuelBRy8hUaSrCzqvwURv7qJzlxF3UGfXQj5sfQHaMGDn3EiIAcvlpRf9bNasVZmwgKLHz4NXKEFuAO7ukkuY1enQqdXF0oRMf8/87OOTG/70uGeWdrUPM8x+iPplDmjMHecMuWHkuJ7H2cB8b0yADT1hOCc9hIEMs556POB31+l+Ze9jGOF3t9K6DgwNX+V4msP6+and7JUUDzW9MPeD0PzU2QaYZLQDdhXU3o1YMkrXg1e8VWop2jFGY47chwsVc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
