travis:
  secure:
    BINSTAR_TOKEN: TLJw68jtWG5SuMvbOIfQyKr1Y4EsPLrr5kzWM+5t0rzk5AFSUPX9WOtMvUkGNQYZkvn9343V96asZWMCSirTdLiaz6EWb5+HcED7vx259SqCVpunuWQ62gS5wLocqiTMJ0jKHZ2RxTKrG+YAywmvpYfY1flAz/luEcbvKXxLzmmZEOeE6UEvinTkgwRtvGTIZOrHS2+LX67Bl/D30BVAwaVRRt5f9Oki6EbLZrsl0fvKBUgg5vWySP2YbGmGwSgikAsRapZI3qwpXAxeMLFQK3TrwVH4vWc/5ilfvMtKcFfdFe/nFHjlh+QJ9sDZ9stQfwoD/4U1OQOwJqiuZQXQyeM93pL0v7LtCgoLtFhGGsAcIb6rTdA+NUZMmlVM9R0L6iFrZOba9Fte6MfRqSuhoUYqBv5JkYzOmaROf7Em9CNFay1NlQHjKbq6RoDp0G4Jas5ae1wtPUKUSEJf+RU6h7VpSzjGGLaeEX95+lR+h1yHYsqfdbMSSCy2VfI/Tt9J48Y3Xj6VzaskJylU1WLbRqWx9+nRClmrh6bq1nHxRyX+/FeuGYtf/mZawlm7NhgkPhfDsVctkHVs8DdtuVuO6QZBIjvT75zXeAGmdD1srkEOvWp7scIxW8lY4cn5eEk/JxiHND+k54UySSolBqvbH5lc5ltpfqi44kXRgYmTvlA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
